var annotated_dup =
[
    [ "cgl", "namespacecgl.html", [
      [ "drawables", "namespacecgl_1_1drawables.html", [
        [ "Ellipse", "classcgl_1_1drawables_1_1Ellipse.html", "classcgl_1_1drawables_1_1Ellipse" ],
        [ "Line", "classcgl_1_1drawables_1_1Line.html", "classcgl_1_1drawables_1_1Line" ],
        [ "Mesh", "classcgl_1_1drawables_1_1Mesh.html", "classcgl_1_1drawables_1_1Mesh" ],
        [ "Point", "classcgl_1_1drawables_1_1Point.html", "classcgl_1_1drawables_1_1Point" ],
        [ "Polygon", "classcgl_1_1drawables_1_1Polygon.html", "classcgl_1_1drawables_1_1Polygon" ],
        [ "Rectangle", "classcgl_1_1drawables_1_1Rectangle.html", "classcgl_1_1drawables_1_1Rectangle" ],
        [ "Triangle", "classcgl_1_1drawables_1_1Triangle.html", "classcgl_1_1drawables_1_1Triangle" ]
      ] ],
      [ "filters", "namespacecgl_1_1filters.html", [
        [ "BaseData", "structcgl_1_1filters_1_1BaseData.html", "structcgl_1_1filters_1_1BaseData" ],
        [ "CharacterShuffleColored", "structcgl_1_1filters_1_1CharacterShuffleColored.html", "structcgl_1_1filters_1_1CharacterShuffleColored" ],
        [ "CharacterShuffleColoredData", "classcgl_1_1filters_1_1CharacterShuffleColoredData.html", "classcgl_1_1filters_1_1CharacterShuffleColoredData" ],
        [ "GeometryElementData", "structcgl_1_1filters_1_1GeometryElementData.html", "structcgl_1_1filters_1_1GeometryElementData" ],
        [ "Grayscale", "structcgl_1_1filters_1_1Grayscale.html", "structcgl_1_1filters_1_1Grayscale" ],
        [ "Invert", "structcgl_1_1filters_1_1Invert.html", "structcgl_1_1filters_1_1Invert" ],
        [ "SingleCharacterColored", "structcgl_1_1filters_1_1SingleCharacterColored.html", "structcgl_1_1filters_1_1SingleCharacterColored" ],
        [ "SingleCharacterColoredData", "structcgl_1_1filters_1_1SingleCharacterColoredData.html", "structcgl_1_1filters_1_1SingleCharacterColoredData" ],
        [ "SolidColor", "structcgl_1_1filters_1_1SolidColor.html", "structcgl_1_1filters_1_1SolidColor" ],
        [ "SolidColorData", "structcgl_1_1filters_1_1SolidColorData.html", "structcgl_1_1filters_1_1SolidColorData" ],
        [ "TextureSampler", "structcgl_1_1filters_1_1TextureSampler.html", "structcgl_1_1filters_1_1TextureSampler" ],
        [ "TextureSamplerData", "structcgl_1_1filters_1_1TextureSamplerData.html", "structcgl_1_1filters_1_1TextureSamplerData" ],
        [ "UVGradient", "structcgl_1_1filters_1_1UVGradient.html", "structcgl_1_1filters_1_1UVGradient" ]
      ] ],
      [ "BaseFilter", "classcgl_1_1BaseFilter.html", "classcgl_1_1BaseFilter" ],
      [ "BaseFilterableBuffer", "classcgl_1_1BaseFilterableBuffer.html", "classcgl_1_1BaseFilterableBuffer" ],
      [ "BitmapFont", "classcgl_1_1BitmapFont.html", "classcgl_1_1BitmapFont" ],
      [ "CharacterCell", "structcgl_1_1CharacterCell.html", "structcgl_1_1CharacterCell" ],
      [ "Clock", "classcgl_1_1Clock.html", "classcgl_1_1Clock" ],
      [ "Color", "classcgl_1_1Color.html", "classcgl_1_1Color" ],
      [ "Console", "classcgl_1_1Console.html", "classcgl_1_1Console" ],
      [ "ConsoleEvent", "structcgl_1_1ConsoleEvent.html", null ],
      [ "DeviceError", "classcgl_1_1DeviceError.html", "classcgl_1_1DeviceError" ],
      [ "Drawable", "classcgl_1_1Drawable.html", "classcgl_1_1Drawable" ],
      [ "Error", "classcgl_1_1Error.html", "classcgl_1_1Error" ],
      [ "ErrorSettings", "classcgl_1_1ErrorSettings.html", "classcgl_1_1ErrorSettings" ],
      [ "Event", "classcgl_1_1Event.html", "classcgl_1_1Event" ],
      [ "EventManager", "classcgl_1_1EventManager.html", "classcgl_1_1EventManager" ],
      [ "EventType", "structcgl_1_1EventType.html", "structcgl_1_1EventType" ],
      [ "Filter", "classcgl_1_1Filter.html", "classcgl_1_1Filter" ],
      [ "FilterableBuffer", "classcgl_1_1FilterableBuffer.html", "classcgl_1_1FilterableBuffer" ],
      [ "FilterPipeline", "classcgl_1_1FilterPipeline.html", "classcgl_1_1FilterPipeline" ],
      [ "Framework", "classcgl_1_1Framework.html", "classcgl_1_1Framework" ],
      [ "GlobalMemory", "classcgl_1_1GlobalMemory.html", "classcgl_1_1GlobalMemory" ],
      [ "InvalidArgumentError", "classcgl_1_1InvalidArgumentError.html", "classcgl_1_1InvalidArgumentError" ],
      [ "InvalidEvent", "structcgl_1_1InvalidEvent.html", null ],
      [ "KeyPressEvent", "structcgl_1_1KeyPressEvent.html", null ],
      [ "KeyReleaseEvent", "structcgl_1_1KeyReleaseEvent.html", null ],
      [ "LogicError", "classcgl_1_1LogicError.html", "classcgl_1_1LogicError" ],
      [ "Matrix3", "classcgl_1_1Matrix3.html", "classcgl_1_1Matrix3" ],
      [ "MouseMoveEvent", "structcgl_1_1MouseMoveEvent.html", null ],
      [ "MouseScrollEvent", "structcgl_1_1MouseScrollEvent.html", null ],
      [ "TermiosError", "classcgl_1_1TermiosError.html", "classcgl_1_1TermiosError" ],
      [ "Texture", "classcgl_1_1Texture.html", "classcgl_1_1Texture" ],
      [ "Transform", "classcgl_1_1Transform.html", "classcgl_1_1Transform" ],
      [ "Transformable", "classcgl_1_1Transformable.html", "classcgl_1_1Transformable" ],
      [ "Vector2", "classcgl_1_1Vector2.html", "classcgl_1_1Vector2" ],
      [ "WinapiError", "classcgl_1_1WinapiError.html", "classcgl_1_1WinapiError" ]
    ] ]
];