var annotated_dup =
[
    [ "til", "namespacetil.html", [
      [ "filters", "namespacetil_1_1filters.html", [
        [ "BaseData", "structtil_1_1filters_1_1BaseData.html", "structtil_1_1filters_1_1BaseData" ],
        [ "CharacterShuffleColored", "structtil_1_1filters_1_1CharacterShuffleColored.html", "structtil_1_1filters_1_1CharacterShuffleColored" ],
        [ "CharacterShuffleColoredData", "classtil_1_1filters_1_1CharacterShuffleColoredData.html", "classtil_1_1filters_1_1CharacterShuffleColoredData" ],
        [ "Grayscale", "structtil_1_1filters_1_1Grayscale.html", "structtil_1_1filters_1_1Grayscale" ],
        [ "Invert", "structtil_1_1filters_1_1Invert.html", "structtil_1_1filters_1_1Invert" ],
        [ "SingleCharacterColored", "structtil_1_1filters_1_1SingleCharacterColored.html", "structtil_1_1filters_1_1SingleCharacterColored" ],
        [ "SingleCharacterColoredData", "structtil_1_1filters_1_1SingleCharacterColoredData.html", "structtil_1_1filters_1_1SingleCharacterColoredData" ],
        [ "SingleColoredDithered", "structtil_1_1filters_1_1SingleColoredDithered.html", "structtil_1_1filters_1_1SingleColoredDithered" ],
        [ "SingleColoredDitheredData", "structtil_1_1filters_1_1SingleColoredDitheredData.html", "structtil_1_1filters_1_1SingleColoredDitheredData" ],
        [ "SolidColor", "structtil_1_1filters_1_1SolidColor.html", "structtil_1_1filters_1_1SolidColor" ],
        [ "SolidColorData", "structtil_1_1filters_1_1SolidColorData.html", "structtil_1_1filters_1_1SolidColorData" ],
        [ "TextureSampler", "structtil_1_1filters_1_1TextureSampler.html", "structtil_1_1filters_1_1TextureSampler" ],
        [ "TextureSamplerData", "structtil_1_1filters_1_1TextureSamplerData.html", "structtil_1_1filters_1_1TextureSamplerData" ],
        [ "UVGradient", "structtil_1_1filters_1_1UVGradient.html", "structtil_1_1filters_1_1UVGradient" ],
        [ "VertexData", "structtil_1_1filters_1_1VertexData.html", "structtil_1_1filters_1_1VertexData" ]
      ] ],
      [ "primitives", "namespacetil_1_1primitives.html", [
        [ "Ellipse", "structtil_1_1primitives_1_1Ellipse.html", "structtil_1_1primitives_1_1Ellipse" ],
        [ "Line", "structtil_1_1primitives_1_1Line.html", "structtil_1_1primitives_1_1Line" ],
        [ "TriangleMesh", "structtil_1_1primitives_1_1TriangleMesh.html", "structtil_1_1primitives_1_1TriangleMesh" ],
        [ "Vertex", "structtil_1_1primitives_1_1Vertex.html", "structtil_1_1primitives_1_1Vertex" ]
      ] ],
      [ "BaseFilter", "classtil_1_1BaseFilter.html", "classtil_1_1BaseFilter" ],
      [ "BaseFilterableBuffer", "classtil_1_1BaseFilterableBuffer.html", "classtil_1_1BaseFilterableBuffer" ],
      [ "BitmapFont", "classtil_1_1BitmapFont.html", "classtil_1_1BitmapFont" ],
      [ "CharacterCell", "structtil_1_1CharacterCell.html", "structtil_1_1CharacterCell" ],
      [ "Clock", "classtil_1_1Clock.html", "classtil_1_1Clock" ],
      [ "Color", "classtil_1_1Color.html", "classtil_1_1Color" ],
      [ "Console", "classtil_1_1Console.html", "classtil_1_1Console" ],
      [ "ConsoleEvent", "structtil_1_1ConsoleEvent.html", null ],
      [ "DeviceError", "classtil_1_1DeviceError.html", "classtil_1_1DeviceError" ],
      [ "Drawable", "classtil_1_1Drawable.html", "classtil_1_1Drawable" ],
      [ "DrawCall", "structtil_1_1DrawCall.html", "structtil_1_1DrawCall" ],
      [ "DrawCallData", "structtil_1_1DrawCallData.html", "structtil_1_1DrawCallData" ],
      [ "EllipseDrawable", "classtil_1_1EllipseDrawable.html", "classtil_1_1EllipseDrawable" ],
      [ "Error", "classtil_1_1Error.html", "classtil_1_1Error" ],
      [ "ErrorSettings", "classtil_1_1ErrorSettings.html", "classtil_1_1ErrorSettings" ],
      [ "Event", "classtil_1_1Event.html", "classtil_1_1Event" ],
      [ "EventManager", "classtil_1_1EventManager.html", "classtil_1_1EventManager" ],
      [ "EventType", "structtil_1_1EventType.html", "structtil_1_1EventType" ],
      [ "Filter", "classtil_1_1Filter.html", "classtil_1_1Filter" ],
      [ "FilterableBuffer", "classtil_1_1FilterableBuffer.html", "classtil_1_1FilterableBuffer" ],
      [ "FilterPipeline", "classtil_1_1FilterPipeline.html", "classtil_1_1FilterPipeline" ],
      [ "Framework", "classtil_1_1Framework.html", "classtil_1_1Framework" ],
      [ "GlobalMemory", "classtil_1_1GlobalMemory.html", "classtil_1_1GlobalMemory" ],
      [ "InvalidArgumentError", "classtil_1_1InvalidArgumentError.html", "classtil_1_1InvalidArgumentError" ],
      [ "InvalidEvent", "structtil_1_1InvalidEvent.html", null ],
      [ "KeyPressEvent", "structtil_1_1KeyPressEvent.html", null ],
      [ "KeyReleaseEvent", "structtil_1_1KeyReleaseEvent.html", null ],
      [ "LineDrawable", "classtil_1_1LineDrawable.html", "classtil_1_1LineDrawable" ],
      [ "LogicError", "classtil_1_1LogicError.html", "classtil_1_1LogicError" ],
      [ "Matrix3", "classtil_1_1Matrix3.html", "classtil_1_1Matrix3" ],
      [ "MouseMoveEvent", "structtil_1_1MouseMoveEvent.html", null ],
      [ "MouseScrollEvent", "structtil_1_1MouseScrollEvent.html", null ],
      [ "Point", "classtil_1_1Point.html", "classtil_1_1Point" ],
      [ "Polygon", "classtil_1_1Polygon.html", "classtil_1_1Polygon" ],
      [ "Rectangle", "classtil_1_1Rectangle.html", "classtil_1_1Rectangle" ],
      [ "Renderer", "classtil_1_1Renderer.html", "classtil_1_1Renderer" ],
      [ "RenderTarget", "classtil_1_1RenderTarget.html", "classtil_1_1RenderTarget" ],
      [ "Sprite", "classtil_1_1Sprite.html", "classtil_1_1Sprite" ],
      [ "TermiosError", "classtil_1_1TermiosError.html", "classtil_1_1TermiosError" ],
      [ "Texture", "classtil_1_1Texture.html", "classtil_1_1Texture" ],
      [ "Transform", "classtil_1_1Transform.html", "classtil_1_1Transform" ],
      [ "Vector2", "classtil_1_1Vector2.html", "classtil_1_1Vector2" ],
      [ "WinapiError", "classtil_1_1WinapiError.html", "classtil_1_1WinapiError" ],
      [ "Window", "classtil_1_1Window.html", "classtil_1_1Window" ],
      [ "WindowManager", "classtil_1_1WindowManager.html", "classtil_1_1WindowManager" ]
    ] ]
];